### ISSUE TITLE
Error when using a plugin

### ISSUE THREAD

**Issue by nysthee** [kaarolch/kubernetes-jmeter#3]
Hi 

I encounter the following issue when trying to run a test that uses a plugin (https://github.com/GSLabDev/pepper-box).

```java
Error in rconfigure() method java.rmi.ServerException: RemoteException occurred in server thread; nested exception is:
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is:
        java.lang.ClassNotFoundException: com.gslab.pepper.config.plaintext.PlainTextConfigElement (no security manager: RMI class loader disabled)
Error in rconfigure() method java.rmi.ServerException: RemoteException occurred in server thread; nested exception is:
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is:
        java.lang.ClassNotFoundException: com.gslab.pepper.config.plaintext.PlainTextConfigElement (no security manager: RMI class loader disabled)
Remote engines have been started
```

Could you please advise on this, and how I can fix this.

Thanks for the great work!

**Comment by kaarolch** [comment]
@nysthee I was quite busy last week, I would check it during weekend.

**Comment by nysthee** [comment]
Hi solved it by making sure plugins are on all the nodes. It was ignorance from my side.

**Comment by pritukam** [comment]
Hi @nysthee,

I am getting the same exception when trying to execute my load testing on the slave nodes. I have copied the pepper-box.jar on all the nodes to location lib/ext initially (later to lib/ as well in addition to the one in lib/ext), but I still get the same ClassNotFoundException. I understand the problem you faced was 2 years ago, however, any pointers on this will help a lot. Thanks.
